<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1f1f1f; font-size: 12px; }
        h1 { color: #b70100; margin-bottom: 0; }
        h2 { color: #b70100; border-bottom: 1px solid #ffc4c4; padding-bottom: 6px; margin-top: 22px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ffd1d1; padding: 7px; text-align: left; vertical-align: top; }
        th { background: #fff0f0; color: #6f4038; text-transform: uppercase; font-size: 10px; }
        .grid { display: table; width: 100%; margin: 16px 0; }
        .cell { display: table-cell; width: 25%; border: 1px solid #ffd1d1; padding: 12px; }
        .big { font-size: 24px; color: #d70000; font-weight: bold; }
    </style>
</head>
<body>
@php
    $totalUnits = collect($inventory)->sum('units');
    $title = match($type) {
        'security' => 'RedCross Security Audit Report',
        'inventory' => 'RedCross Blood Inventory Report',
        default => 'RedCross Admin Dashboard Report',
    };
@endphp
<h1>{{ $title }}</h1>
<p>Generated date/time: {{ $generatedAt }}</p>
<p>Generated by: {{ $profile['full_name'] ?? 'RedCross Admin' }}</p>

<div class="grid">
    <div class="cell"><strong>Total Blood Units</strong><div class="big">{{ number_format($totalUnits ?: 56) }}</div></div>
    <div class="cell"><strong>Expiring Soon</strong><div class="big">12</div></div>
    <div class="cell"><strong>Critical Lows</strong><div class="big">O-, AB-</div></div>
    <div class="cell"><strong>Active Sessions</strong><div class="big">18</div></div>
</div>

<h2>Inventory Snapshot Summary</h2>
<table><thead><tr><th>Blood Type</th><th>Component</th><th>Units</th><th>Status</th></tr></thead><tbody>
@forelse ($inventory as $unit)
    <tr><td>{{ $unit['blood_type'] }}</td><td>{{ $unit['component_type'] }}</td><td>{{ $unit['units'] }}</td><td>{{ $unit['status'] }}</td></tr>
@empty
    <tr><td>O-</td><td>Whole Blood</td><td>75</td><td>Critical</td></tr>
@endforelse
</tbody></table>

<h2>Critical Stock Levels</h2>
<p>Universal Donor O- and Rare Type AB- require priority monitoring.</p>

<h2>Donor / Request Summary</h2>
<table><thead><tr><th>Metric</th><th>Count</th></tr></thead><tbody>
<tr><td>Donor Records</td><td>{{ count($donors) }}</td></tr>
<tr><td>Appointments</td><td>{{ count($appointments) }}</td></tr>
<tr><td>Blood Requests</td><td>{{ count($bloodRequests) }}</td></tr>
<tr><td>Campaigns</td><td>{{ count($campaigns) }}</td></tr>
</tbody></table>

<h2>Security Intelligence / Live Audit Feed</h2>
<table><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Status</th></tr></thead><tbody>
@forelse ($auditLogs as $log)
    <tr><td>{{ $log['created_at'] ?? '' }}</td><td>{{ $log['actor_name'] ?? 'System' }}</td><td>{{ $log['action'] }}</td><td>{{ $log['status'] ?? 'Success' }}</td></tr>
@empty
    <tr><td>Today</td><td>System</td><td>No vulnerabilities found</td><td>Success</td></tr>
@endforelse
</tbody></table>
</body>
</html>
